version: 2.1
orbs:
  browser-tools: circleci/browser-tools@2.1.2
jobs:
  build:
    docker:
      # Specify the version you desire here
      - image: cimg/php:8.4.8-browsers

    steps:
      - checkout
      - browser-tools/install-browser-tools
      - browser-tools/install_chrome
      - browser-tools/install_chromedriver
      - browser-tools/install_firefox
      - browser-tools/install_firefoxdriver
      # Download and cache dependencies
      - restore_cache:
          keys:
            # "composer.lock" can be used if it is committed to the repo
            - v1-dependencies-{{ checksum "composer.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: "Install sqlite"
          command: |
            sudo add-apt-repository -y ppa:ondrej/php
            sudo apt-get install php8.4-sqlite3
            touch database/database.sqlite

      - run:
          name: "Create Environment file"
          command: |
            mv .env.testing .env

      - run:
          name: "Install Dependencies"
          command: composer install -n --prefer-dist

#      - run:
#          name: Run migration
#          command: |
#            php artisan migrate

#      - run:
#          name: "Generate App key"
#          command: php artisan key:generate

#      - run:
#          name: "Generate Passport encryption keys"
#          command: php artisan passport:install

      - save_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor

      - run:
          name: "Run Tests"
          command: ./vendor/bin/phpunit

      - run:
          name: "removes .env to ensure it doesn't override the one already on server"
          command: |
            mv .env .env.testing
      - run:
          name: "deploy to staging"
          command: |
            ".circleci/scripts/deploy.sh"
       # run tests with phpunit
#      - slack/notify:
#          event: fail
#          custom: |
#            {
#              "text": "CircleCI job failed - custom message",
#              "blocks": [
#                {
#                  "type": "header",
#                  "text": {
#                    "type": "plain_text",
#                    "text": "Job Failed. :red_circle:",
#                    "emoji": true
#                  }
#                },
#                {
#                  "type": "section",
#                  "fields": [
#                    {
#                      "type": "mrkdwn",
#                      "text": "*Job*: ${CIRCLE_JOB}"
#                    }
#                  ]
#                },
#                {
#                  "type": "section",
#                  "fields": [
#                    {
#                      "type": "mrkdwn",
#                      "text": "*Project*:\n$CIRCLE_PROJECT_REPONAME"
#                    },
#                    {
#                      "type": "mrkdwn",
#                      "text": "*Branch*:\n$CIRCLE_BRANCH"
#                    },
#                    {
#                      "type": "mrkdwn",
#                      "text": "*Author*:\n$CIRCLE_USERNAME"
#                    }
#                  ],
#                  "accessory": {
#                    "type": "image",
#                    "image_url": "https://assets.brandfolder.com/otz5mn-bw4j2w-6jzqo8/original/circle-logo-badge-black.png",
#                    "alt_text": "CircleCI logo"
#                  }
#                },
#                {
#                  "type": "section",
#                  "fields": [
#                    {
#                      "type": "mrkdwn",
#                      "text": "*Commit Message*:\n$GIT_COMMIT_DESC"
#                    },
#                    {
#                      "type": "mrkdwn",
#                      "text": "*Mentions*:\n$SLACK_PARAM_MENTIONS"
#                    }
#                  ]
#                },
#                {
#                  "type": "actions",
#                  "elements": [
#                    {
#                      "type": "button",
#                      "text": {
#                        "type": "plain_text",
#                        "type": "plain_text",
#                        "text": "View Job"
#                      },
#                      "url": "${CIRCLE_BUILD_URL}"
#                    }
#                  ]
#                }
#              ]
#            }
#      - slack/notify:
#          event: pass
#          custom: |
#            {
#              "text": "CircleCI job succeeded - custom message!",
#              "blocks": [
#                {
#                  "type": "header",
#                  "text": {
#                    "type": "plain_text",
#                    "text": "Job Succeeded. :white_check_mark:",
#                    "emoji": true
#                  }
#                },
#                {
#                  "type": "section",
#                  "fields": [
#                    {
#                      "type": "mrkdwn",
#                      "text": "*Job*: ${CIRCLE_JOB}"
#                    }
#                  ]
#                },
#                {
#                  "type": "section",
#                  "fields": [
#                    {
#                      "type": "mrkdwn",
#                      "text": "*Project*:\n$CIRCLE_PROJECT_REPONAME"
#                    },
#                    {
#                      "type": "mrkdwn",
#                      "text": "*Branch*:\n$CIRCLE_BRANCH"
#                    },
#                    {
#                      "type": "mrkdwn",
#                      "text": "*Commit*:\n$CIRCLE_SHA1"
#                    },
#                    {
#                      "type": "mrkdwn",
#                      "text": "*Author*:\n$CIRCLE_USERNAME"
#                    },
#                    {
#                      "type": "mrkdwn",
#                      "text": "*Commit Message*:\n$GIT_COMMIT_DESC"
#                    }
#                  ],
#                  "accessory": {
#                    "type": "image",
#                    "image_url": "https://assets.brandfolder.com/otz5mn-bw4j2w-6jzqo8/original/circle-logo-badge-black.png",
#                    "alt_text": "CircleCI logo"
#                  }
#                },
#                {
#                  "type": "actions",
#                  "elements": [
#                    {
#                      "type": "button",
#                      "text": {
#                        "type": "plain_text",
#                        "text": "View Job"
#                      },
#                      "url": "${CIRCLE_BUILD_URL}"
#                    }
#                  ]
#                }
#              ]
#            }

workflows:
  version: 2
  workflow:
    jobs:
      - build:
          filters:
            branches:
              only: master
